import {
  OPTIONAL_DESCRIPTION_HINT,
  requirementFormSchema,
  type FormField,
  type FormOption,
  type RequirementForm,
} from "./form";

export const SPORTS_BUSINESS_ID = "seed-business-sports";
export const SPORTS_BUSINESS_NAME = "فروشگاه اینترنتی ورزشی";

type FieldInput = Partial<FormField> & Pick<FormField, "key" | "type" | "label">;

function field(input: FieldInput): FormField {
  return {
    required: false,
    options: [],
    allowOther: false,
    countAsFeature: false,
    showInSummary: false,
    ...input,
  };
}

const opt = (id: string, label: string, hint?: string): FormOption => ({ id, label, hint });

const CITIES = [
  "تهران",
  "کرج",
  "اصفهان",
  "مشهد",
  "شیراز",
  "تبریز",
  "اهواز",
  "قم",
  "رشت",
  "کرمان",
  "یزد",
  "ارومیه",
  "کیش",
].map((city) => opt(city, city));

/**
 * Sports-store requirements form as data. Field keys mirror the TV form shape so
 * shared validation, migration helpers and the generic wizard all work unchanged.
 */
const SPORTS_FORM_INPUT: RequirementForm = {
  steps: [
    {
      id: "store",
      title: "فروشگاه",
      description: "معرفی کسب‌وکار و وضعیت فعلی",
      fields: [
        field({
          key: "contactName",
          type: "text",
          label: "نام رابط فروشگاه",
          hint: "نام کسی که درباره پروژه با ما هماهنگ می‌کند",
          placeholder: "مثلاً علی محمدی",
          required: true,
          minLength: 3,
          requiredMessage: "نام رابط فروشگاه را کامل وارد کنید.",
          role: "contactName",
          showInSummary: true,
          summaryLabel: "رابط",
        }),
        field({
          key: "storeName",
          type: "text",
          label: "نام فروشگاه",
          hint: "نامی که مشتریان شما می‌شناسند",
          placeholder: "مثلاً فیت‌استور",
          required: true,
          minLength: 2,
          requiredMessage: "نام فروشگاه را وارد کنید.",
          role: "storeName",
          showInSummary: true,
          summaryLabel: "فروشگاه",
        }),
        field({
          key: "businessType",
          type: "single",
          label: "نوع فعالیت",
          hint: "نوع فعالیت تعیین می‌کند سایت چقدر فروش حضوری و آنلاین را پوشش دهد",
          required: true,
          requiredMessage: "نوع فعالیت فروشگاه را انتخاب کنید.",
          options: [
            opt("physical", "فروشگاه حضوری", "شعبه فروش پوشاک و لوازم ورزشی دارید"),
            opt("online", "فقط آنلاین", "می‌خواهید فروش فقط از سایت انجام شود"),
            opt("both", "حضوری + آنلاین", "سایت کنار شعبه، مثل فروشگاه‌های بزرگ ورزشی"),
          ],
          allowOther: true,
          otherPlaceholder: "نوع فعالیت خود را بنویسید",
          showInSummary: true,
        }),
        field({
          key: "city",
          type: "select",
          label: "شهر فعالیت",
          hint: "شهر اصلی فعالیت برای تنظیم ارسال و پشتیبانی",
          required: true,
          requiredMessage: "شهر فعالیت را انتخاب کنید.",
          options: [...CITIES, opt("سایر", "سایر شهرها")],
          defaultValue: "تهران",
          role: "city",
          summaryLabel: "شهر",
        }),
        field({
          key: "existingWebsite",
          type: "single",
          label: "وضعیت وب‌سایت فعلی",
          hint: "اگر سایت دارید، زمان راه‌اندازی معمولاً کمتر می‌شود",
          required: true,
          requiredMessage: "وضعیت سایت فعلی را مشخص کنید.",
          options: [
            opt("none", "سایت ندارم", "از صفر می‌خواهیم بسازیم"),
            opt("have", "سایت دارم", "می‌خواهیم ارتقا یا جایگزین شود"),
            opt("redesign", "نیاز به بازطراحی", "سایت فعلی جواب نمی‌دهد"),
          ],
          allowOther: true,
          otherPlaceholder: "وضعیت سایت فعلی خود را توضیح دهید",
          showInSummary: true,
          summaryLabel: "وب‌سایت فعلی",
        }),
        field({
          key: "storeDescription",
          type: "textarea",
          label: "توضیح کوتاه درباره فروشگاه",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder:
            "چند سال است لوازم ورزشی می‌فروشید؟ مشتری‌هایتان بیشتر ورزشکار، باشگاه و خانواده هستند یا خرید اینترنتی؟",
        }),
      ],
    },
    {
      id: "catalog",
      title: "کاتالوگ",
      description: "چه برندها و دسته‌هایی باید در سایت باشد",
      fields: [
        field({
          key: "brandsToSell",
          type: "multi",
          label: "برندها",
          hint: "برندهایی که می‌خواهید در فروشگاه ورزشی‌تان بفروشید",
          required: true,
          requiredMessage: "حداقل یک برند برای فروش انتخاب کنید.",
          options: [
            opt("nike", "نایکی"),
            opt("adidas", "آدیداس"),
            opt("puma", "پوما"),
            opt("underarmour", "آندر آرمور"),
            opt("newbalance", "نیو بالانس"),
            opt("asics", "اسیکس"),
            opt("reebok", "ریباک"),
            opt("local", "برندهای ایرانی", "تولید داخل یا برند اختصاصی خودتان"),
          ],
          allowOther: true,
          otherLabel: "برندهای دیگر",
          otherPlaceholder: "برندهای دیگری که می‌فروشید",
          showInSummary: true,
        }),
        field({
          key: "sizeRanges",
          type: "multi",
          label: "دسته‌های کالا",
          hint: "دسته‌هایی که کاتالوگ سایت باید پوشش دهد؛ مثل کفش، پوشاک و تجهیزات",
          required: true,
          requiredMessage: "حداقل یک دسته کالا انتخاب کنید.",
          options: [
            opt("men", "پوشاک ورزشی مردانه", "تیشرت، شلوار، گرمکن و لباس تمرین"),
            opt("women", "پوشاک ورزشی زنانه", "لباس تمرین، رانینگ و باشگاه"),
            opt("kids", "بچگانه", "پوشاک و کفش ورزشی کودک"),
            opt("footwear", "کفش ورزشی", "رانینگ، فوتبال، بسکتبال و روزمره"),
            opt("team", "ورزش‌های تیمی", "توپ، لباس تیم و لوازم فوتبال و بسکتبال"),
            opt("fitness", "تجهیزات بدنسازی", "دمبل، کش، مت و لوازم باشگاه خانگی"),
            opt("outdoor", "فضای باز", "کوهنوردی، کمپ و دوچرخه"),
            opt("accessories", "اکسسوری", "جوراب، کلاه، بطری، ساک و مچ‌بند"),
            opt("all", "همه دسته‌ها", "کاتالوگ کامل مثل یک فروشگاه بزرگ ورزشی"),
          ],
          allowOther: true,
          otherPlaceholder: "دسته دیگری که می‌خواهید در سایت باشد",
          showInSummary: true,
          summaryLabel: "دسته‌های کالا",
        }),
        field({
          key: "productVolume",
          type: "single",
          label: "حجم کاتالوگ",
          hint: "تعداد تقریبی کالاها با احتساب رنگ و سایز",
          required: true,
          requiredMessage: "حجم تقریبی کاتالوگ را مشخص کنید.",
          options: [
            opt("small", "کمتر از ۳۰۰ کالا", "فروشگاه تخصصی با تنوع محدود"),
            opt("medium", "۳۰۰ تا ۳ هزار کالا", "با احتساب رنگ و سایز"),
            opt("large", "بیش از ۳ هزار کالا", "کاتالوگ گسترده مثل نمشی"),
          ],
          allowOther: true,
          otherPlaceholder: "حجم تقریبی کاتالوگ خود را بنویسید",
          showInSummary: true,
          summaryLabel: "حجم کاتالوگ",
        }),
        field({
          key: "inventorySources",
          type: "multi",
          label: "ورود محصولات",
          hint: "کالاها و موجودی هر سایز چطور وارد سایت می‌شوند",
          required: true,
          requiredMessage: "نحوه ورود محصولات را انتخاب کنید.",
          options: [
            opt("manual", "ثبت دستی", "کالا، رنگ و سایز را در پنل وارد می‌کنیم"),
            opt("excel", "اکسل / CSV", "ورود گروهی از فایل تأمین‌کننده"),
            opt("api", "API تأمین‌کننده", "اتصال به موجودی برند یا پخش‌کننده"),
            opt("erp", "نرم‌افزار حسابداری", "یکپارچه با موجودی شعبه"),
            opt("variants", "موجودی هر سایز و رنگ", "هر ترکیب جداگانه کم و زیاد شود"),
          ],
          allowOther: true,
          otherPlaceholder: "نحوه ورود محصولات را توضیح دهید",
          showInSummary: true,
        }),
      ],
    },
    {
      id: "buyer",
      title: "تجربه خرید",
      description: "مشتری فروشگاه شما در سایت چه می‌بیند",
      fields: [
        field({
          key: "buyerFeatures",
          type: "multi",
          label: "امکانات تجربه خرید",
          hint: "امکاناتی که مشتری فروشگاه شما هنگام خرید لباس و کفش می‌بیند",
          required: true,
          requiredMessage: "حداقل یک امکانات برای تجربه خرید مشتری انتخاب کنید.",
          options: [
            opt("variants", "انتخاب رنگ و سایز", "مشتری روی خود کالا سایز و رنگ را عوض کند"),
            opt("sizeguide", "راهنمای سایز", "جدول اندازه لباس و کفش قبل از خرید"),
            opt("filters", "فیلتر پیشرفته", "رشته ورزشی، جنسیت، برند، سایز، رنگ و قیمت"),
            opt("search", "جستجوی سریع", "پیشنهاد کالا هنگام تایپ نام برند یا مدل"),
            opt("wishlist", "لیست علاقه‌مندی", "ذخیره برای خرید بعدی"),
            opt("reviews", "نظر خریداران", "امتیاز، عکس و تجربه سایز روی کالا"),
            opt("outfit", "کالای مکمل", "مثلاً کنار کفش رانینگ، جوراب و لباس پیشنهاد شود"),
            opt("sale", "صفحه حراج", "کمپین تخفیف و کالاهای پرفروش"),
            opt("chat", "چت با فروشگاه", "پرسش درباره سایز و موجودی"),
            opt("blog", "مجله ورزشی", "راهنمای انتخاب کفش، برنامه تمرین و معرفی کالا"),
          ],
          allowOther: true,
          otherPlaceholder: "امکانات دیگری که برای مشتری می‌خواهید",
          countAsFeature: true,
          showInSummary: true,
          summaryLabel: "تجربه خرید",
        }),
        field({
          key: "buyerNotes",
          type: "textarea",
          label: "توضیحات بیشتر درباره تجربه خرید",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "مثلاً مشتری باید قبل از خرید، جدول سایز کفش و هزینه ارسال را ببیند",
          summaryLabel: "توضیحات تجربه خرید",
        }),
      ],
    },
    {
      id: "payment",
      title: "پرداخت و خدمات",
      description: "درگاه، ارسال، تعویض سایز و گارانتی",
      fields: [
        field({
          key: "paymentGateways",
          type: "multi",
          label: "درگاه پرداخت",
          hint: "روش‌های پرداختی که می‌خواهید برای خریدار فعال باشد.",
          required: true,
          requiredMessage: "حداقل یک روش پرداخت انتخاب کنید.",
          options: [
            opt("zarinpal", "زرین‌پال"),
            opt("idpay", "آیدی‌پی"),
            opt("snappay", "اسنپ‌پی"),
            opt("card", "کارت‌به‌کارت + تأیید دستی"),
            opt("installment", "اقساط / اعتباری", "برای کفش و پوشاک گران‌تر"),
            opt("cod", "پرداخت در محل", "رایج در خرید پوشاک و کفش"),
          ],
          allowOther: true,
          otherPlaceholder: "روش پرداخت دیگری که می‌خواهید",
          countAsFeature: true,
          showInSummary: true,
        }),
        field({
          key: "deliveryMethods",
          type: "multi",
          label: "روش ارسال",
          hint: "ارسال و تعویض سایز برای مشتری فروشگاه.",
          required: true,
          requiredMessage: "حداقل یک روش ارسال انتخاب کنید.",
          options: [
            opt("standard", "ارسال عادی", "تحویل درب منزل در چند روز"),
            opt("express", "ارسال سریع", "همان‌روز یا روز بعد در شهرهای اصلی"),
            opt("pickup", "تحویل از شعبه", "مشتری سفارش آنلاین را از فروشگاه می‌گیرد"),
            opt("exchange", "ارسال تعویض سایز", "مسیر جدا برای برگرداندن کفش و لباس"),
          ],
          allowOther: true,
          otherPlaceholder: "روش ارسال دیگری که می‌خواهید",
          countAsFeature: true,
          showInSummary: true,
        }),
        field({
          key: "purchaseServices",
          type: "multi",
          label: "خدمات هنگام خرید",
          hint: "خدماتی که خریدار موقع سفارش باید ببیند.",
          options: [
            opt(
              "installationOnSite",
              "مرجوعی و تعویض سایز",
              "خریدار بتواند لباس یا کفش نامناسب را برگرداند یا عوض کند",
            ),
            opt("warrantyDisplay", "نمایش گارانتی", "گارانتی تجهیزات و اصالت کالا روی صفحه محصول"),
            opt("transparentCheckout", "شفافیت قبل از پرداخت", "همه هزینه‌ها قبل از درگاه دیده شود"),
          ],
          countAsFeature: true,
          showInSummary: true,
          summaryLabel: "خدمات خرید",
        }),
        field({
          key: "servicesNotes",
          type: "textarea",
          label: "توضیحات خدمات و ارسال",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "مثلاً تعویض سایز کفش تا ۷ روز و ارسال رایگان بالای مبلغ مشخص",
        }),
      ],
    },
    {
      id: "admin",
      title: "پنل مدیریت",
      description: "ابزارهایی که شما به آن نیاز دارید",
      fields: [
        field({
          key: "adminFeatures",
          type: "multi",
          label: "ابزارهای پنل مدیریت",
          hint: "ابزارهایی که خودتان در پنل مدیریت به آن نیاز دارید.",
          required: true,
          requiredMessage: "حداقل یک ابزار مدیریتی برای پنل خود انتخاب کنید.",
          options: [
            opt("orders", "مدیریت سفارش", "وضعیت پرداخت، بسته‌بندی و ارسال"),
            opt("returns", "مرجوعی و تعویض", "درخواست تعویض سایز و بازگشت وجه"),
            opt("inventory", "موجودی سایز و رنگ", "کالاهای ناموجود و پرفروش به تفکیک تنوع"),
            opt("campaigns", "کمپین تخفیف", "درصد تخفیف روی دسته، برند یا کد تخفیف"),
            opt("sms", "پیامک به مشتری", "اطلاع ارسال، موجود شدن سایز و حراج"),
            opt("staff", "چند کاربره", "دسترسی جدا برای انبار، پشتیبانی و مدیر"),
          ],
          allowOther: true,
          otherPlaceholder: "ابزار مدیریتی دیگری که نیاز دارید",
          countAsFeature: true,
          showInSummary: true,
          summaryLabel: "پنل مدیریت",
        }),
        field({
          key: "adminNotes",
          type: "textarea",
          label: "نیازهای دیگر در پنل مدیریت",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "مثلاً خروجی اکسل سفارش‌ها یا اتصال به پیامک",
        }),
      ],
    },
    {
      id: "design",
      title: "طراحی",
      description: "ظاهر، برند و سایت‌های الهام‌بخش",
      fields: [
        field({
          key: "designStyle",
          type: "single",
          label: "سبک طراحی",
          hint: "حس کلی ظاهر سایت.",
          required: true,
          requiredMessage: "سبک طراحی مورد نظر را انتخاب کنید.",
          options: [
            opt("modern", "مدرن و تصویرمحور", "عکس بزرگ کالا، منوی دسته و خرید سریع با موبایل"),
            opt("premium", "برند ورزشی سطح بالا", "حس فروشگاه‌هایی مثل نایکی و آدیداس"),
            opt("budget", "حراج و تخفیف‌محور", "قیمت خط‌خورده و کمپین در صفحه اول"),
            opt("custom", "طراحی سفارشی", "الهام از سایت‌هایی که خودتان معرفی می‌کنید"),
          ],
          allowOther: true,
          otherPlaceholder: "سبک طراحی دلخواه خود را بنویسید",
          showInSummary: true,
        }),
        field({
          key: "referenceSites",
          type: "textarea",
          label: "سایت‌های مرجع",
          hint: "آدرس سایت‌هایی که از ظاهرشان الهام گرفته‌اید (اختیاری).",
          placeholder: "مثلاً namshi.com، نایکی یا آدیداس",
        }),
        field({
          key: "designAssets",
          type: "multi",
          label: "دارایی‌های برند",
          hint: "موارد برند و اولویت نمایش در موبایل.",
          options: [
            opt("hasLogo", "لوگو آماده دارم"),
            opt("hasBrandGuide", "راهنمای برند دارم", "رنگ، فونت یا هویت بصری"),
            opt("darkMode", "تم تیره"),
            opt("mobileFirst", "اولویت موبایل", "بیشتر خریداران پوشاک از گوشی سفارش می‌دهند"),
          ],
          showInSummary: true,
          summaryLabel: "دارایی‌های طراحی",
        }),
        field({
          key: "designNotes",
          type: "textarea",
          label: "توضیحات طراحی",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "هر نکته‌ای که برای ظاهر سایت مهم است",
        }),
      ],
    },
  ],
};

export const SPORTS_REQUIREMENT_FORM: RequirementForm =
  requirementFormSchema.parse(SPORTS_FORM_INPUT);
