import {
  OPTIONAL_DESCRIPTION_HINT,
  requirementFormSchema,
  type FormField,
  type FormOption,
  type RequirementForm,
} from "./form";

export const TV_BUSINESS_ID = "seed-business-tv";
export const TV_BUSINESS_NAME = "کالای دیجیتال - تلویزیون";

type FieldInput = Partial<FormField> & Pick<FormField, "key" | "type" | "label">;

function field(input: FieldInput): FormField {
  return {
    required: false,
    options: [],
    allowOther: false,
    countAsFeature: false,
    showInSummary: false,
    ...input,
  };
}

const opt = (id: string, label: string, hint?: string): FormOption => ({ id, label, hint });

const CITIES = [
  "تهران",
  "کرج",
  "اصفهان",
  "مشهد",
  "شیراز",
  "تبریز",
  "اهواز",
  "قم",
  "رشت",
  "کرمان",
  "یزد",
  "ارومیه",
  "کیش",
].map((city) => opt(city, city));

/**
 * The original TV-store requirements form, as data. Field keys match the keys
 * the hard-coded form used, so existing answers keep working.
 */
const TV_FORM_INPUT: RequirementForm = {
  steps: [
    {
      id: "store",
      title: "فروشگاه",
      description: "معرفی کسب‌وکار و وضعیت فعلی",
      fields: [
        field({
          key: "contactName",
          type: "text",
          label: "نام رابط فروشگاه",
          hint: "نام کسی که درباره پروژه با ما هماهنگ می‌کند",
          placeholder: "مثلاً علی محمدی",
          required: true,
          minLength: 3,
          requiredMessage: "نام رابط فروشگاه را کامل وارد کنید.",
          role: "contactName",
          showInSummary: true,
          summaryLabel: "رابط",
        }),
        field({
          key: "storeName",
          type: "text",
          label: "نام فروشگاه",
          hint: "نامی که مشتریان شما می‌شناسند",
          placeholder: "مثلاً فریمان الکترونیک",
          required: true,
          minLength: 2,
          requiredMessage: "نام فروشگاه را وارد کنید.",
          role: "storeName",
          showInSummary: true,
          summaryLabel: "فروشگاه",
        }),
        field({
          key: "businessType",
          type: "single",
          label: "نوع فعالیت",
          hint: "نوع فعالیت تعیین می‌کند سایت چقدر فروش حضوری و آنلاین را پوشش دهد",
          required: true,
          requiredMessage: "نوع فعالیت فروشگاه را انتخاب کنید.",
          options: [
            opt("physical", "فروشگاه حضوری", "شعبه یا ویترین فیزیکی دارید"),
            opt("online", "فقط آنلاین", "الان هم بدون حضوری می‌فروشید"),
            opt("both", "حضوری + آنلاین", "می‌خواهید سایت مکمل فروشگاه باشد"),
          ],
          allowOther: true,
          otherPlaceholder: "نوع فعالیت خود را بنویسید",
          showInSummary: true,
        }),
        field({
          key: "city",
          type: "select",
          label: "شهر فعالیت",
          hint: "شهر اصلی فعالیت برای تنظیم ارسال و پشتیبانی",
          required: true,
          requiredMessage: "شهر فعالیت را انتخاب کنید.",
          options: [...CITIES, opt("سایر", "سایر شهرها")],
          defaultValue: "تهران",
          role: "city",
          summaryLabel: "شهر",
        }),
        field({
          key: "existingWebsite",
          type: "single",
          label: "وضعیت وب‌سایت فعلی",
          hint: "اگر سایت دارید، زمان راه‌اندازی معمولاً کمتر می‌شود",
          required: true,
          requiredMessage: "وضعیت سایت فعلی را مشخص کنید.",
          options: [
            opt("none", "سایت ندارم", "از صفر می‌خواهیم بسازیم"),
            opt("have", "سایت دارم", "می‌خواهیم ارتقا یا جایگزین شود"),
            opt("redesign", "نیاز به بازطراحی", "سایت فعلی جواب نمی‌دهد"),
          ],
          allowOther: true,
          otherPlaceholder: "وضعیت سایت فعلی خود را توضیح دهید",
          showInSummary: true,
          summaryLabel: "وب‌سایت فعلی",
        }),
        field({
          key: "storeDescription",
          type: "textarea",
          label: "توضیح کوتاه درباره فروشگاه",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder:
            "چند سال است فروش تلویزیون می‌کنید؟ مشتری‌های شما بیشتر حضوری می‌خرند یا آنلاین؟",
        }),
      ],
    },
    {
      id: "catalog",
      title: "کاتالوگ",
      description: "چه محصولاتی باید در سایت باشد",
      fields: [
        field({
          key: "brandsToSell",
          type: "multi",
          label: "برندها",
          hint: "برندهایی که می‌خواهید در سایت بفروشید",
          required: true,
          requiredMessage: "حداقل یک برند برای فروش انتخاب کنید.",
          options: [
            opt("samsung", "سامسونگ"),
            opt("lg", "ال‌جی"),
            opt("sony", "سونی"),
            opt("tcl", "تی‌سی‌ال"),
            opt("xvision", "ایکس‌ویژن"),
            opt("snowa", "اسنوا"),
            opt("hisense", "هایسنس"),
          ],
          allowOther: true,
          otherLabel: "برندهای دیگر",
          otherPlaceholder: "برندهای دیگری که می‌فروشید",
          showInSummary: true,
        }),
        field({
          key: "sizeRanges",
          type: "multi",
          label: "بازه سایز",
          hint: "بازه سایزهایی که می‌خواهید در کاتالوگ پوشش دهید",
          required: true,
          requiredMessage: "حداقل یک بازه سایز انتخاب کنید.",
          options: [
            opt("small", "۳۲ تا ۴۳ اینچ", "اتاق خواب و فضاهای کوچک"),
            opt("medium", "۵۰ تا ۵۵ اینچ", "پرفروش‌ترین بازه خانگی"),
            opt("large", "۶۵ تا ۷۵ اینچ", "پذیرایی و سینمای خانگی"),
            opt("xlarge", "۸۵ اینچ و بالاتر", "فضاهای بزرگ و لوکس"),
            opt("all", "همه سایزها", "کاتالوگ کامل می‌خواهم"),
          ],
          allowOther: true,
          otherPlaceholder: "بازه سایز دلخواه خود را بنویسید",
          showInSummary: true,
          summaryLabel: "سایز تلویزیون",
        }),
        field({
          key: "productVolume",
          type: "single",
          label: "تعداد مدل",
          hint: "تعداد تقریبی مدل‌های تلویزیون در سایت",
          required: true,
          requiredMessage: "حجم تقریبی کاتالوگ را مشخص کنید.",
          options: [
            opt("small", "کمتر از ۵۰ مدل", "فروشگاه تخصصی و محدود"),
            opt("medium", "۵۰ تا ۲۰۰ مدل", "تنوع متوسط محصول"),
            opt("large", "بیش از ۲۰۰ مدل", "کاتالوگ گسترده مثل مارکت‌پلیس"),
          ],
          allowOther: true,
          otherPlaceholder: "حجم تقریبی کاتالوگ خود را بنویسید",
          showInSummary: true,
        }),
        field({
          key: "inventorySources",
          type: "multi",
          label: "ورود محصولات",
          hint: "محصولات چطور وارد سایت می‌شوند",
          required: true,
          requiredMessage: "نحوه ورود محصولات را انتخاب کنید.",
          options: [
            opt("manual", "ثبت دستی", "محصولات را در پنل وارد می‌کنیم"),
            opt("excel", "اکسل / CSV", "ورود گروهی از فایل"),
            opt("api", "API تأمین‌کننده", "اتصال به سیستم توزیع‌کننده"),
            opt("erp", "نرم‌افزار حسابداری", "یکپارچه با موجودی فعلی"),
          ],
          allowOther: true,
          otherPlaceholder: "نحوه ورود محصولات را توضیح دهید",
          showInSummary: true,
        }),
      ],
    },
    {
      id: "buyer",
      title: "تجربه خرید",
      description: "مشتری نهایی در سایت چه می‌بیند",
      fields: [
        field({
          key: "buyerFeatures",
          type: "multi",
          label: "امکانات تجربه خرید",
          hint: "امکاناتی که مشتری نهایی در سایت می‌بیند — نه ابزارهای پنل شما",
          required: true,
          requiredMessage: "حداقل یک امکانات برای تجربه خرید مشتری انتخاب کنید.",
          options: [
            opt(
              "configurator",
              "پیکربندی مرحله‌ای",
              "مشتری سایز، برند و خدمات را قدم‌به‌قدم انتخاب کند",
            ),
            opt("comparison", "مقایسه محصول", "کنار هم گذاشتن چند مدل"),
            opt("filters", "فیلتر پیشرفته", "اینچ، برند، پنل، قیمت و ..."),
            opt("wishlist", "لیست علاقه‌مندی", "ذخیره برای بعد"),
            opt("installment", "خرید اقساطی", "نمایش طرح‌های پرداخت"),
            opt("chat", "چت با فروشگاه", "پشتیبانی آنلاین مشتری"),
            opt("reviews", "نظرات مشتریان", "امتیاز و دیدگاه روی محصول"),
            opt("blog", "مجله / راهنما", "مقاله انتخاب تلویزیون و اخبار"),
          ],
          allowOther: true,
          otherPlaceholder: "امکانات دیگری که برای مشتری می‌خواهید",
          countAsFeature: true,
          showInSummary: true,
          summaryLabel: "تجربه خرید",
        }),
        field({
          key: "buyerNotes",
          type: "textarea",
          label: "توضیحات بیشتر درباره تجربه خرید",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "مثلاً می‌خواهم مشتری قبل از پرداخت هزینه ارسال و نصب را ببیند",
          summaryLabel: "توضیحات تجربه خرید",
        }),
      ],
    },
    {
      id: "payment",
      title: "پرداخت و خدمات",
      description: "درگاه، ارسال، نصب و گارانتی",
      fields: [
        field({
          key: "paymentGateways",
          type: "multi",
          label: "درگاه پرداخت",
          hint: "درگاه‌ها و روش‌های پرداختی که می‌خواهید فعال باشد.",
          required: true,
          requiredMessage: "حداقل یک روش پرداخت انتخاب کنید.",
          options: [
            opt("zarinpal", "زرین‌پال"),
            opt("idpay", "آیدی‌پی"),
            opt("snappay", "اسنپ‌پی"),
            opt("card", "کارت‌به‌کارت + تأیید دستی"),
            opt("installment", "اقساط / اعتباری"),
          ],
          allowOther: true,
          otherPlaceholder: "روش پرداخت دیگری که می‌خواهید",
          countAsFeature: true,
          showInSummary: true,
        }),
        field({
          key: "deliveryMethods",
          type: "multi",
          label: "روش ارسال",
          hint: "روش‌های ارسال برای مشتری.",
          required: true,
          requiredMessage: "حداقل یک روش ارسال انتخاب کنید.",
          options: [
            opt("standard", "ارسال عادی", "تحویل درب واحد"),
            opt("express", "ارسال سریع", "بازه زمانی کوتاه‌تر"),
            opt("inhome", "تحویل داخل منزل", "مناسب تلویزیون‌های بزرگ"),
            opt("pickup", "تحویل حضوری", "مشتری از فروشگاه می‌برد"),
          ],
          allowOther: true,
          otherPlaceholder: "روش ارسال دیگری که می‌خواهید",
          countAsFeature: true,
          showInSummary: true,
        }),
        field({
          key: "purchaseServices",
          type: "multi",
          label: "خدمات هنگام خرید",
          hint: "خدمات اضافه‌ای که هنگام خرید به مشتری نشان داده می‌شود.",
          options: [
            opt("installationOnSite", "سفارش نصب در محل", "مشتری هنگام خرید نصب دیواری را انتخاب کند"),
            opt("warrantyDisplay", "نمایش گارانتی", "گارانتی شرکتی و طلایی روی سایت"),
            opt("transparentCheckout", "شفافیت قبل از پرداخت", "همه هزینه‌ها قبل از درگاه دیده شود"),
          ],
          countAsFeature: true,
          showInSummary: true,
          summaryLabel: "خدمات خرید",
        }),
        field({
          key: "servicesNotes",
          type: "textarea",
          label: "توضیحات خدمات و ارسال",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "مثلاً ارسال داخل منزل فقط برای ۶۵ اینچ به بالا",
        }),
      ],
    },
    {
      id: "admin",
      title: "پنل مدیریت",
      description: "ابزارهایی که شما به آن نیاز دارید",
      fields: [
        field({
          key: "adminFeatures",
          type: "multi",
          label: "ابزارهای پنل مدیریت",
          hint: "ابزارهایی که خودتان در پنل مدیریت به آن نیاز دارید.",
          required: true,
          requiredMessage: "حداقل یک ابزار مدیریتی برای پنل خود انتخاب کنید.",
          options: [
            opt("orders", "مدیریت سفارش", "پیگیری وضعیت و پرداخت"),
            opt("leads", "ثبت سرنخ", "درخواست‌های ناتمام و تماس"),
            opt("inventory", "گزارش موجودی", "کالاهای کم‌موجود و پرفروش"),
            opt("sms", "پیامک کمپین", "اطلاع‌رسانی تخفیف و موجودی"),
            opt("staff", "چند کاربره", "دسترسی جدا برای کارکنان"),
          ],
          allowOther: true,
          otherPlaceholder: "ابزار مدیریتی دیگری که نیاز دارید",
          countAsFeature: true,
          showInSummary: true,
          summaryLabel: "پنل مدیریت",
        }),
        field({
          key: "adminNotes",
          type: "textarea",
          label: "نیازهای دیگر در پنل مدیریت",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "مثلاً خروجی اکسل سفارش‌ها یا اتصال به پیامک",
        }),
      ],
    },
    {
      id: "design",
      title: "طراحی",
      description: "ظاهر، برند و سایت‌های الهام‌بخش",
      fields: [
        field({
          key: "designStyle",
          type: "single",
          label: "سبک طراحی",
          hint: "حس کلی ظاهر سایت.",
          required: true,
          requiredMessage: "سبک طراحی مورد نظر را انتخاب کنید.",
          options: [
            opt("modern", "مدرن و مینیمال", "تمیز، سریع، موبایل‌محور"),
            opt("premium", "لوکس و حرفه‌ای", "حس برند سطح بالا"),
            opt("budget", "اقتصادی و پرمعامله", "تخفیف و قیمت در مرکز"),
            opt("custom", "طراحی سفارشی", "الهام از سایت‌های مرجع خودم"),
          ],
          allowOther: true,
          otherPlaceholder: "سبک طراحی دلخواه خود را بنویسید",
          showInSummary: true,
        }),
        field({
          key: "referenceSites",
          type: "textarea",
          label: "سایت‌های مرجع",
          hint: "آدرس سایت‌هایی که از ظاهرشان الهام گرفته‌اید (اختیاری).",
          placeholder: "مثلاً دیجی‌کالا، تکنولایف، سامسونگ ایران",
        }),
        field({
          key: "designAssets",
          type: "multi",
          label: "دارایی‌های برند",
          hint: "موارد برند و اولویت نمایش در موبایل.",
          options: [
            opt("hasLogo", "لوگو آماده دارم"),
            opt("hasBrandGuide", "راهنمای برند دارم", "رنگ، فونت یا هویت بصری"),
            opt("darkMode", "تم تیره"),
            opt("mobileFirst", "اولویت موبایل", "بیشتر مشتریان از گوشی می‌خرند"),
          ],
          showInSummary: true,
          summaryLabel: "دارایی‌های طراحی",
        }),
        field({
          key: "designNotes",
          type: "textarea",
          label: "توضیحات طراحی",
          hint: OPTIONAL_DESCRIPTION_HINT,
          placeholder: "هر نکته‌ای که برای ظاهر سایت مهم است",
        }),
      ],
    },
  ],
};

export const TV_REQUIREMENT_FORM: RequirementForm = requirementFormSchema.parse(TV_FORM_INPUT);

/** Starting point for a business created from scratch in the admin panel. */
export function blankRequirementForm(): RequirementForm {
  return requirementFormSchema.parse({
    steps: [
      {
        id: "intro",
        title: "معرفی کسب‌وکار",
        description: "اطلاعات پایه کسب‌وکار شما",
        fields: [
          field({
            key: "contactName",
            type: "text",
            label: "نام رابط",
            placeholder: "مثلاً علی محمدی",
            required: true,
            minLength: 3,
            role: "contactName",
            showInSummary: true,
            summaryLabel: "رابط",
          }),
          field({
            key: "storeName",
            type: "text",
            label: "نام کسب‌وکار",
            required: true,
            minLength: 2,
            role: "storeName",
            showInSummary: true,
            summaryLabel: "کسب‌وکار",
          }),
        ],
      },
    ],
  });
}
