import { catalogEntry } from "./pricing-catalog";
import type { CatalogEntry } from "./pricing-catalog";
import { SHARED_PRICING_CATALOG } from "./pricing-catalog-shared";

const BUYER = {
  id: "buyer",
  title: "تجربه خرید",
  subtitle: "امکانات سمت مشتری در فروشگاه تلویزیون",
};

const ADMIN = {
  id: "admin",
  title: "پنل مدیریت",
  subtitle: "ابزارهای مدیریتی فروشگاه",
};

const TV_PRICING_CATALOG: CatalogEntry[] = [
  catalogEntry({
    id: "tv-buyer-configurator",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "configurator",
    title: "پیکربندی مرحله‌ای",
    description: "انتخاب سایز، برند و خدمات به‌صورت گام‌به‌گام قبل از خرید.",
    weight: 4,
  }),
  catalogEntry({
    id: "tv-buyer-comparison",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "comparison",
    title: "مقایسه محصول",
    description: "کنار هم گذاشتن مشخصات چند مدل تلویزیون.",
    weight: 3,
  }),
  catalogEntry({
    id: "tv-buyer-filters",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "filters",
    title: "فیلتر پیشرفته",
    description: "فیلتر اینچ، برند، پنل، قیمت و سایر مشخصات فنی.",
    weight: 3,
  }),
  catalogEntry({
    id: "tv-buyer-wishlist",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "wishlist",
    title: "لیست علاقه‌مندی",
    description: "ذخیره مدل‌ها برای خرید بعدی.",
    weight: 2,
  }),
  catalogEntry({
    id: "tv-buyer-installment",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "installment",
    title: "نمایش خرید اقساطی",
    description: "محاسبه و نمایش طرح‌های پرداخت روی صفحه محصول.",
    weight: 4,
  }),
  catalogEntry({
    id: "tv-buyer-reviews",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "reviews",
    title: "نظرات مشتریان",
    description: "امتیاز، دیدگاه و پرسش‌وپاسخ روی صفحه محصول.",
    weight: 3,
  }),
  catalogEntry({
    id: "tv-buyer-blog",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "blog",
    title: "مجله / راهنمای خرید",
    description: "مقالات انتخاب تلویزیون، اخبار و جذب از جستجو.",
    weight: 3,
  }),
  catalogEntry({
    id: "tv-delivery-inhome",
    sectionId: "delivery",
    sectionTitle: "ارسال",
    sectionSubtitle: "روش‌های تحویل سفارش",
    fieldKey: "deliveryMethods",
    optionId: "inhome",
    title: "تحویل داخل منزل",
    description: "هماهنگی تحویل درب منزل برای تلویزیون‌های بزرگ.",
    weight: 4,
  }),
  catalogEntry({
    id: "tv-admin-orders",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "orders",
    title: "مدیریت سفارش",
    description: "پیگیری وضعیت، پرداخت و ارسال سفارش‌ها.",
    weight: 2,
  }),
  catalogEntry({
    id: "tv-admin-leads",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "leads",
    title: "ثبت سرنخ",
    description: "درخواست‌های ناتمام و تماس‌های پیگیری.",
    weight: 3,
  }),
  catalogEntry({
    id: "tv-admin-inventory",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "inventory",
    title: "گزارش موجودی",
    description: "کالاهای کم‌موجود، پرفروش و هشدار موجودی.",
    weight: 3,
  }),
  catalogEntry({
    id: "tv-admin-sms",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "sms",
    title: "پیامک کمپین",
    description: "اطلاع‌رسانی تخفیف، موجودی و وضعیت سفارش.",
    weight: 3,
  }),
  catalogEntry({
    id: "tv-admin-staff",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "staff",
    title: "پنل چند کاربره",
    description: "نقش‌ها و دسترسی جدا برای کارکنان.",
    weight: 4,
  }),
  catalogEntry({
    id: "tv-catalog-all-sizes",
    sectionId: "inventory",
    sectionTitle: "ورود کالا",
    sectionSubtitle: "اتصال موجودی و ورود گروهی محصولات",
    fieldKey: "sizeRanges",
    optionId: "all",
    title: "پوشش همه سایزها",
    description: "ساختار کاتالوگ برای تمام بازه‌های اینچ.",
    weight: 3,
  }),
];

export function tvPricingCatalog(): CatalogEntry[] {
  return [...TV_PRICING_CATALOG, ...SHARED_PRICING_CATALOG];
}
