import { catalogEntry } from "./pricing-catalog";
import type { CatalogEntry } from "./pricing-catalog";
import { SHARED_PRICING_CATALOG } from "./pricing-catalog-shared";

const BUYER = {
  id: "buyer",
  title: "تجربه خرید",
  subtitle: "امکانات سمت مشتری در فروشگاه ورزشی",
};

const ADMIN = {
  id: "admin",
  title: "پنل مدیریت",
  subtitle: "ابزارهای مدیریتی فروشگاه",
};

const SPORTS_PRICING_CATALOG: CatalogEntry[] = [
  catalogEntry({
    id: "sport-buyer-variants",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "variants",
    title: "انتخاب رنگ و سایز",
    description: "تغییر سایز و رنگ روی صفحه محصول با موجودی لحظه‌ای.",
    weight: 4,
  }),
  catalogEntry({
    id: "sport-buyer-sizeguide",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "sizeguide",
    title: "راهنمای سایز",
    description: "جدول اندازه لباس و کفش قبل از افزودن به سبد.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-buyer-filters",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "filters",
    title: "فیلتر پیشرفته",
    description: "فیلتر رشته ورزشی، جنسیت، برند، سایز، رنگ و قیمت.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-buyer-search",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "search",
    title: "جستجوی سریع",
    description: "پیشنهاد کالا هنگام تایپ نام برند یا مدل.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-buyer-wishlist",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "wishlist",
    title: "لیست علاقه‌مندی",
    description: "ذخیره برای خرید بعدی.",
    weight: 2,
  }),
  catalogEntry({
    id: "sport-buyer-reviews",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "reviews",
    title: "نظر خریداران",
    description: "امتیاز، عکس و تجربه سایز روی کالا.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-buyer-outfit",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "outfit",
    title: "کالای مکمل",
    description: "پیشنهاد اکسسوری و لباس مرتبط کنار محصول اصلی.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-buyer-sale",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "sale",
    title: "صفحه حراج",
    description: "کمپین تخفیف و نمایش کالاهای پرفروش.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-buyer-blog",
    sectionId: BUYER.id,
    sectionTitle: BUYER.title,
    sectionSubtitle: BUYER.subtitle,
    fieldKey: "buyerFeatures",
    optionId: "blog",
    title: "مجله ورزشی",
    description: "راهنمای انتخاب کفش، برنامه تمرین و معرفی کالا.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-pay-cod",
    sectionId: "payment",
    sectionTitle: "پرداخت",
    sectionSubtitle: "درگاه‌ها و روش‌های تسویه",
    fieldKey: "paymentGateways",
    optionId: "cod",
    title: "پرداخت در محل",
    description: "فعال‌سازی COD برای سفارش پوشاک و کفش.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-delivery-exchange",
    sectionId: "delivery",
    sectionTitle: "ارسال",
    sectionSubtitle: "روش‌های تحویل سفارش",
    fieldKey: "deliveryMethods",
    optionId: "exchange",
    title: "ارسال تعویض سایز",
    description: "مسیر جدا برای برگرداندن و تعویض کفش و لباس.",
    weight: 4,
  }),
  catalogEntry({
    id: "sport-admin-orders",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "orders",
    title: "مدیریت سفارش",
    description: "وضعیت پرداخت، بسته‌بندی و ارسال.",
    weight: 2,
  }),
  catalogEntry({
    id: "sport-admin-returns",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "returns",
    title: "مرجوعی و تعویض",
    description: "درخواست تعویض سایز و بازگشت وجه.",
    weight: 4,
  }),
  catalogEntry({
    id: "sport-admin-inventory",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "inventory",
    title: "موجودی سایز و رنگ",
    description: "مدیریت تنوع کالا به تفکیک سایز و رنگ.",
    weight: 4,
  }),
  catalogEntry({
    id: "sport-admin-campaigns",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "campaigns",
    title: "کمپین تخفیف",
    description: "تخفیف روی دسته، برند یا کد تخفیف.",
    weight: 4,
  }),
  catalogEntry({
    id: "sport-admin-sms",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "sms",
    title: "پیامک به مشتری",
    description: "اطلاع ارسال، موجود شدن سایز و حراج.",
    weight: 3,
  }),
  catalogEntry({
    id: "sport-admin-staff",
    sectionId: ADMIN.id,
    sectionTitle: ADMIN.title,
    sectionSubtitle: ADMIN.subtitle,
    fieldKey: "adminFeatures",
    optionId: "staff",
    title: "پنل چند کاربره",
    description: "دسترسی جدا برای انبار، پشتیبانی و مدیر.",
    weight: 4,
  }),
  catalogEntry({
    id: "sport-inv-variants",
    sectionId: "inventory",
    sectionTitle: "ورود کالا",
    sectionSubtitle: "اتصال موجودی و ورود گروهی محصولات",
    fieldKey: "inventorySources",
    optionId: "variants",
    title: "موجودی هر سایز و رنگ",
    description: "کم و زیاد کردن جداگانه هر ترکیب سایز/رنگ.",
    weight: 4,
  }),
  catalogEntry({
    id: "sport-catalog-all",
    sectionId: "inventory",
    sectionTitle: "ورود کالا",
    sectionSubtitle: "اتصال موجودی و ورود گروهی محصولات",
    fieldKey: "sizeRanges",
    optionId: "all",
    title: "پوشش همه دسته‌ها",
    description: "ساختار کاتالوگ برای تمام دسته‌های ورزشی.",
    weight: 3,
  }),
];

export function sportsPricingCatalog(): CatalogEntry[] {
  return [...SPORTS_PRICING_CATALOG, ...SHARED_PRICING_CATALOG];
}
