import { catalogEntry } from "./pricing-catalog";
import type { CatalogEntry } from "./pricing-catalog";

const PAYMENT = {
  id: "payment",
  title: "پرداخت",
  subtitle: "درگاه‌ها و روش‌های تسویه",
};

const DELIVERY = {
  id: "delivery",
  title: "ارسال",
  subtitle: "روش‌های تحویل سفارش",
};

const SERVICES = {
  id: "services",
  title: "خدمات خرید",
  subtitle: "خدمات نمایش‌داده‌شده هنگام سفارش",
};

const INVENTORY = {
  id: "inventory",
  title: "ورود کالا",
  subtitle: "اتصال موجودی و ورود گروهی محصولات",
};

const DESIGN = {
  id: "design",
  title: "طراحی",
  subtitle: "ظاهر، برند و مهاجرت از سایت قبلی",
};

/** Options shared by TV and sports requirement forms (same field keys and option ids). */
export const SHARED_PRICING_CATALOG: CatalogEntry[] = [
  catalogEntry({
    id: "pay-zarinpal",
    sectionId: PAYMENT.id,
    sectionTitle: PAYMENT.title,
    sectionSubtitle: PAYMENT.subtitle,
    fieldKey: "paymentGateways",
    optionId: "zarinpal",
    title: "درگاه زرین‌پال",
    description: "اتصال و تسویه آنلاین سفارش‌ها از طریق زرین‌پال.",
    weight: 2,
  }),
  catalogEntry({
    id: "pay-idpay",
    sectionId: PAYMENT.id,
    sectionTitle: PAYMENT.title,
    sectionSubtitle: PAYMENT.subtitle,
    fieldKey: "paymentGateways",
    optionId: "idpay",
    title: "درگاه آیدی‌پی",
    description: "فعال‌سازی پرداخت آنلاین با آیدی‌پی.",
    weight: 2,
  }),
  catalogEntry({
    id: "pay-snappay",
    sectionId: PAYMENT.id,
    sectionTitle: PAYMENT.title,
    sectionSubtitle: PAYMENT.subtitle,
    fieldKey: "paymentGateways",
    optionId: "snappay",
    title: "درگاه اسنپ‌پی",
    description: "پرداخت از طریق کیف پول اسنپ‌پی.",
    weight: 2,
  }),
  catalogEntry({
    id: "pay-card",
    sectionId: PAYMENT.id,
    sectionTitle: PAYMENT.title,
    sectionSubtitle: PAYMENT.subtitle,
    fieldKey: "paymentGateways",
    optionId: "card",
    title: "کارت‌به‌کارت + تأیید دستی",
    description: "ثبت فیش و تأیید پرداخت توسط اپراتور در پنل.",
    weight: 2,
  }),
  catalogEntry({
    id: "pay-installment",
    sectionId: PAYMENT.id,
    sectionTitle: PAYMENT.title,
    sectionSubtitle: PAYMENT.subtitle,
    fieldKey: "paymentGateways",
    optionId: "installment",
    title: "پرداخت اقساطی / اعتباری",
    description: "نمایش طرح‌های اقساط و اتصال به سرویس اعتباری.",
    weight: 4,
  }),
  catalogEntry({
    id: "delivery-standard",
    sectionId: DELIVERY.id,
    sectionTitle: DELIVERY.title,
    sectionSubtitle: DELIVERY.subtitle,
    fieldKey: "deliveryMethods",
    optionId: "standard",
    title: "ارسال عادی",
    description: "محاسبه هزینه و زمان ارسال استاندارد در checkout.",
    weight: 2,
  }),
  catalogEntry({
    id: "delivery-express",
    sectionId: DELIVERY.id,
    sectionTitle: DELIVERY.title,
    sectionSubtitle: DELIVERY.subtitle,
    fieldKey: "deliveryMethods",
    optionId: "express",
    title: "ارسال سریع",
    description: "بازه تحویل کوتاه‌تر و اولویت‌بندی در انبار.",
    weight: 3,
  }),
  catalogEntry({
    id: "delivery-pickup",
    sectionId: DELIVERY.id,
    sectionTitle: DELIVERY.title,
    sectionSubtitle: DELIVERY.subtitle,
    fieldKey: "deliveryMethods",
    optionId: "pickup",
    title: "تحویل حضوری / از شعبه",
    description: "انتخاب زمان مراجعه مشتری برای دریافت سفارش.",
    weight: 2,
  }),
  catalogEntry({
    id: "svc-installation",
    sectionId: SERVICES.id,
    sectionTitle: SERVICES.title,
    sectionSubtitle: SERVICES.subtitle,
    fieldKey: "purchaseServices",
    optionId: "installationOnSite",
    title: "خدمات هنگام خرید (نصب / مرجوعی)",
    description: "افزودن خدمت انتخابی در checkout مطابق نیازمندی شما.",
    weight: 3,
  }),
  catalogEntry({
    id: "svc-warranty",
    sectionId: SERVICES.id,
    sectionTitle: SERVICES.title,
    sectionSubtitle: SERVICES.subtitle,
    fieldKey: "purchaseServices",
    optionId: "warrantyDisplay",
    title: "نمایش گارانتی و اصالت",
    description: "نمایش گارانتی، اصالت کالا و شرایط پوشش روی صفحه محصول.",
    weight: 2,
  }),
  catalogEntry({
    id: "svc-transparent-checkout",
    sectionId: SERVICES.id,
    sectionTitle: SERVICES.title,
    sectionSubtitle: SERVICES.subtitle,
    fieldKey: "purchaseServices",
    optionId: "transparentCheckout",
    title: "شفافیت هزینه قبل از پرداخت",
    description: "جمع‌بندی همه هزینه‌ها (کالا، ارسال، خدمات) پیش از درگاه.",
    weight: 2,
  }),
  catalogEntry({
    id: "inv-excel",
    sectionId: INVENTORY.id,
    sectionTitle: INVENTORY.title,
    sectionSubtitle: INVENTORY.subtitle,
    fieldKey: "inventorySources",
    optionId: "excel",
    title: "ورود گروهی اکسل / CSV",
    description: "بارگذاری و به‌روزرسانی دسته‌ای کاتالوگ از فایل.",
    weight: 3,
  }),
  catalogEntry({
    id: "inv-api",
    sectionId: INVENTORY.id,
    sectionTitle: INVENTORY.title,
    sectionSubtitle: INVENTORY.subtitle,
    fieldKey: "inventorySources",
    optionId: "api",
    title: "اتصال API تأمین‌کننده",
    description: "همگام‌سازی قیمت و موجودی با سیستم توزیع‌کننده یا برند.",
    weight: 5,
  }),
  catalogEntry({
    id: "inv-erp",
    sectionId: INVENTORY.id,
    sectionTitle: INVENTORY.title,
    sectionSubtitle: INVENTORY.subtitle,
    fieldKey: "inventorySources",
    optionId: "erp",
    title: "یکپارچه با نرم‌افزار حسابداری",
    description: "اتصال موجودی و سفارش به ERP یا حسابداری فعلی.",
    weight: 5,
  }),
  catalogEntry({
    id: "vol-large",
    sectionId: INVENTORY.id,
    sectionTitle: INVENTORY.title,
    sectionSubtitle: INVENTORY.subtitle,
    fieldKey: "productVolume",
    optionId: "large",
    title: "کاتالوگ گسترده",
    description: "ساختار برای تعداد بالای SKU، فیلتر و جستجوی سریع.",
    weight: 4,
  }),
  catalogEntry({
    id: "design-premium",
    sectionId: DESIGN.id,
    sectionTitle: DESIGN.title,
    sectionSubtitle: DESIGN.subtitle,
    fieldKey: "designStyle",
    optionId: "premium",
    title: "طراحی لوکس / حرفه‌ای",
    description: "چیدمان سطح بالا، تایپوگرافی اختصاصی و حس برند premium.",
    weight: 4,
  }),
  catalogEntry({
    id: "design-custom",
    sectionId: DESIGN.id,
    sectionTitle: DESIGN.title,
    sectionSubtitle: DESIGN.subtitle,
    fieldKey: "designStyle",
    optionId: "custom",
    title: "طراحی کاملاً سفارشی",
    description: "طراحی منحصربه‌فرد بر اساس سایت‌های مرجع و دارایی برند شما.",
    weight: 5,
  }),
  catalogEntry({
    id: "design-dark",
    sectionId: DESIGN.id,
    sectionTitle: DESIGN.title,
    sectionSubtitle: DESIGN.subtitle,
    fieldKey: "designAssets",
    optionId: "darkMode",
    title: "تم تیره",
    description: "پوسته تیره با سوییچ روشن/تاریک برای کاربر.",
    weight: 2,
  }),
  catalogEntry({
    id: "design-brand-guide",
    sectionId: DESIGN.id,
    sectionTitle: DESIGN.title,
    sectionSubtitle: DESIGN.subtitle,
    fieldKey: "designAssets",
    optionId: "hasBrandGuide",
    title: "پیاده‌سازی راهنمای برند",
    description: "اعمال رنگ، فونت و قوانین هویت بصری در کل سایت.",
    weight: 3,
  }),
  catalogEntry({
    id: "site-redesign",
    sectionId: DESIGN.id,
    sectionTitle: DESIGN.title,
    sectionSubtitle: DESIGN.subtitle,
    fieldKey: "existingWebsite",
    optionId: "redesign",
    title: "بازطراحی سایت فعلی",
    description: "مهاجرت محتوا و بهبود UX سایت موجود.",
    weight: 4,
  }),
  catalogEntry({
    id: "site-migrate",
    sectionId: DESIGN.id,
    sectionTitle: DESIGN.title,
    sectionSubtitle: DESIGN.subtitle,
    fieldKey: "existingWebsite",
    optionId: "have",
    title: "ارتقا / جایگزینی سایت فعلی",
    description: "انتقال داده و راه‌اندازی روی زیرساخت جدید.",
    weight: 3,
  }),
];
